## Introduction

    NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for Numerical Python.

## Why Use NumPy?
    In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?
    NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


    

### 1 NumPy Arrays

**NumPy Array**
* An array is a data structure that stores values of same data type.
* While python lists can contain values corresponding to different data types, arrays in python can only contain values
    corresponding to the same data type. 
* However python lists fail to deliver the performance required while computing large sets of numerical data. To address this
    issue we use NumPy arrays.
* We can create NumPy arrays by converting a list to an array.


In [1]:
import numpy as np

n1=np.array([10,20,30,40])                      # One dimentioneal array
print(n1,'Data type : ',type(n1))
print(n1[0], '\n')                              # Access a entry from 1D array

n2=np.array([[10,20,30,40],[40,30,20,10]])      # Two dimentioneal array
print(n2)
print(n2[0,2],'\n')                             # Access a entry from 1D array

arr_str_cars = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']
arr_np_list = np.array(arr_str_cars)            # Convert a array in to NumPy array
print(arr_np_list, '\n') 


[10 20 30 40] Data type :  <class 'numpy.ndarray'>
10 

[[10 20 30 40]
 [40 30 20 10]]
30 

['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla'] 



### 2 NumPy Functions

 #### 1. np.arange()
* The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
* It has the following paramaters:
  * start : start of interval range. By default start = 0
  * stop  : end of interval range
  * step  : step size of interval. By default step size = 1

In [10]:
arr1 = np.arange(start=0, stop=10)          # creation without step
print(arr1)
# OR
arr1 = np.arange(0,10)
print(arr1)

arr2 = np.arange(start=0, stop=40, step=5)  # Creation with step input
print(arr2)
#OR
arr2 = np.arange(0,40,5)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15 20 25 30 35]
[ 0  5 10 15 20 25 30 35]


#### 2. np.linspace()
* The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.            
*It has the following parameters:              
 * start: start of interval range. By default start = 0
 * stop: end of interval range
 * num : No. of samples to generate. By default num = 50

In [23]:
mat2 = np.linspace(0,10)            # Creation with undefined number samples, so default sample number is taken as 50
print(mat2)
mat2 = np.linspace(0,10,8)          # Creation with defined number samples, so interval is adjusted according it
print(mat2)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


**How are these values getting generated?**

The step size or the difference between each element will be decided by the following formula:

**(stop - start) / (total elements - 1)**

So, in this case:
(5 - 0) / 49 = 0.10204082

The first value will be 0.10204082, the second value will be 0.10204082 + 0.10204082, the third value will be 0.10204082 + 0.10204082 +0.10204082, and so on.

#### 3. np.zeros()
 
* The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix filled with zeros of the given shape. 
* It has the following parameters:    
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [22]:
arr3 = np.zeros(5)
print(arr3, '\n')
mat3 = np.zeros([3,5])
print(mat3)

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 4. np.ones()

* The np.ones() is another function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix of given shape and type, filled with ones.
* It has the following parameters:  
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [27]:
arr4 = np.ones(5)
print(arr4, '\n')
mat4 = np.ones([3,5])
print(mat4)

[1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 5. np.eye()
* The np.eye() is a function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix with ones on the diagonal and zeros elsewhere. 
* It has the following parameters:
  * n: Number of rows and columns in the output matrix 
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [28]:
mat5 = np.eye(5)
print(mat5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 6. np.reshape()

**We can also convert a one dimension array to a matrix. This can be done by using the np.reshape() function.**

* The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means changing the shape of the given array. 
* By reshaping an array we can add or remove dimensions or change number of elements in each dimension. 
* In order to reshape a NumPy array, we use the reshape method with the given array. 
* **Syntax:** array.reshape(shape) 
  * shape: a tuple given as input, the values in tuple will be the new shape of the array.

In [35]:
arr6 = np.arange(0,15)
print(arr6, '\n')
mat6 = arr6.reshape((3,5))
print(mat6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


* To reshape NumPy array number of elements in array has to be equal to (rows X colums) if more or less and Numpy wont be able decide where to put extra elements or what to fill in matrix in case of less elements.

* Below  case will not work because we have 15 elements which we are trying to fit in a 4 X 5 shape which will require 20 elements.

In [36]:
mat6 = arr4.reshape((4,6))

ValueError: cannot reshape array of size 5 into shape (4,6)

#### 7. NumPy Mathematical Functions

NumPy provides:
1. Trigonometric functions 
2. Exponents and Logarithmic functions

In [40]:
# Trigonometry
val7 = np.sin(45)               # Retriving Sine value
print(val7)
val7 = np.cos(45)               # Retriving Cosine value
print(val7)
val7 = np.tan(45)               # Retriving Tan value
print(val7, '\n')

# Exponent 
exp7 = np.exp(2)
print(exp7)
exp7 = np.arange(1,5)
print(np.exp(exp7), '\n')

# Logarithm
log7 = np.log(2)                # By default NemPy takes base e for the log (Natural Log)
print(log7)
log7 = np.log(exp7)             # Natural log of any array of matrix can be directly calculated
print(log7)
log7 = np.log10(2)              # np.log10() is used for caluclating log with base 10
print(log7)
log7 = np.log2(2)               # np.log2() is used for caluclating log with base 2
print(log7)

0.8509035245341184
0.5253219888177297
1.6197751905438615 

7.38905609893065
[ 2.71828183  7.3890561  20.08553692 54.59815003] 

0.6931471805599453
[0.         0.69314718 1.09861229 1.38629436]
0.3010299956639812
1.0


#### 8. NumPy Matrix arithmatics 

In [55]:
# Operation on array
arr8a = np.arange(1,5)
print(arr8a)
arr8b = np.arange(6,10)
print(arr8b,'\n')

print('Addition         :   ',arr8a+arr8b)
print('Subtraction      :   ',arr8b-arr8a)
print('Multiplication   :   ',arr8a*arr8b)
print('Division         :   ',arr8b/arr8a)
print('Inversion        :   ',1/arr8b)
print('Power            :   ',arr8a**arr8b, '\n')

# Operation on matrix
mat8a = np.arange(1,26).reshape(5,5)
print(mat8a, '\n')
mat8b = np.eye(5)
print(mat8b, '\n')
print('Addition         :   ','\n',mat8a+mat8b, '\n')
print('Subtraction      :   ','\n',mat8a-mat8b, '\n')
print('Multiplication   :   ','\n',mat8a*mat8b, '\n')
print('Division         :   ','\n',mat8b/mat8a, '\n')

[1 2 3 4]
[6 7 8 9] 

Addition         :    [ 7  9 11 13]
Subtraction      :    [5 5 5 5]
Multiplication   :    [ 6 14 24 36]
Division         :    [6.         3.5        2.66666667 2.25      ]
Inversion        :    [0.16666667 0.14285714 0.125      0.11111111]
Power            :    [     1    128   6561 262144] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Addition         :    
 [[ 2.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10.]
 [11. 12. 14. 14. 15.]
 [16. 17. 18. 20. 20.]
 [21. 22. 23. 24. 26.]] 

Subtraction      :    
 [[ 0.  2.  3.  4.  5.]
 [ 6.  6.  8.  9. 10.]
 [11. 12. 12. 14. 15.]
 [16. 17. 18. 18. 20.]
 [21. 22. 23. 24. 24.]] 

Multiplication   :    
 [[ 1.  0.  0.  0.  0.]
 [ 0.  7.  0.  0.  0.]
 [ 0.  0. 13.  0.  0.]
 [ 0.  0.  0. 19.  0.]
 [ 0.  0.  0.  0. 25.]] 

Division         :    
 [[1.         0.         0.         0.         0.

#### 9. Linear algebra matrix Operations

* Matrix Multiplication
* Matrix Transpose

In [62]:
mat9a = np.arange(1,10).reshape(3,3)
print(mat9a,'\n',)
mat9b = np.eye(3)
print(mat9b,'\n')

print('Multiplication   :   ','\n',mat9a@mat9b, '\n')               # Matrix Multiplication
print('Transpose 1st Way:   ','\n',np.transpose(mat9a), '\n')       # Matrix Transpose 1st way
print('Transpose 2nd way:   ','\n',mat9a.T, '\n')                   # Matrix Transpose 2nd way

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Multiplication   :    
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

Transpose 1st Way:    
 [[1 4 7]
 [2 5 8]
 [3 6 9]] 

Transpose 2nd way:    
 [[1 4 7]
 [2 5 8]
 [3 6 9]] 



#### 10. np.max() And np.min()

In [63]:
mat10 = np.arange(1,10).reshape(3,3)
print(mat10,'\n')

print("Maximum  : ", np.max(mat10))
print("Minimum  : ", np.min(mat10))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Maximum  :  9
Minimum  :  1


#### 11. np.random

* **1.** The np.random.rand returns a random NumPy array whose element(s) are drawn randomly from the normal distribution over
    [0,1]. (including 0 but excluding 1). 
* Syntax - **np.random.rand(d0,d1)**
  * d0,d1 – It represents the dimension of the required array given as int, where d1 is optional.

* **2.** The np.random.randn returns a random numpy array whose sample(s) are drawn randomly from the standard normal distribution (Mean as 0 and standard deviation as 1)
* Syntax - **np.random.randn(d0,d1)**
  * d0,d1 – It represents the dimension of the output, where d1 is optional.

* **3.** The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the
    high (exclusive) range. 
* Syntax - **np.random.randint(low, high, size)**
  * low – It represents the lowest inclusive bound of the distribution from where the sample can be drawn.
  * high – It represents the upper exclusive bound of the distribution from where the sample can be drawn. 
  * size – It represents the shape of the output.

In [72]:
# Random numbers from Normal Distribution [above 0 to brlow 1]
rand11a = np.random.rand(5)
print('One dimentional array with random values : ','\n',rand11a,'\n')
rand11b = np.random.rand(5,5)
print('Two dimentional matrix with random values : ','\n',rand11b,'\n')

# Random numbers from Standard Normal Distribution [Mean 0 and Standard Deviation 1]
rand11a = np.random.randn(5)
print('One dimentional array with random values : ','\n',rand11a,'\n')
rand11b = np.random.randn(5,5)
print('Two dimentional matrix with random values : ','\n',rand11b,'\n')

# Random numbers from mentioned Upper and lower limit
rand11a = np.random.randint(0,5,10)
print('One dimentional array with random values : ','\n',rand11a,'\n')
rand11b = np.random.randint(0,5,[5,5])
print('Two dimentional matrix with random values : ','\n',rand11b,'\n')

One dimentional array with random values :  
 [0.58864977 0.68721764 0.03484455 0.57216457 0.38792424] 

Two dimentional matrix with random values :  
 [[0.34329703 0.94087059 0.39773054 0.12856784 0.15781614]
 [0.33719557 0.0631153  0.19544004 0.58640731 0.1834858 ]
 [0.59275139 0.79956105 0.99332788 0.39434833 0.57232263]
 [0.66421106 0.57849772 0.50671916 0.23165306 0.04664307]
 [0.51909832 0.58648519 0.38634266 0.68583194 0.01159784]] 

One dimentional array with random values :  
 [0.71318022 0.06695561 0.56904648 0.50705285 0.56200575] 

Two dimentional matrix with random values :  
 [[ 0.12239932 -0.26476113 -0.59232957  0.32260665 -1.0301219 ]
 [-1.03917263 -0.51175423  1.00055932  0.40937145  0.95899377]
 [ 0.76646025  1.05817438 -0.75595375 -0.04977997 -0.44246902]
 [-0.5620621  -0.73759908  0.24061309 -1.92338144  0.79267878]
 [ 1.59057766  1.85075718  0.71713953  0.09063824  0.31220327]] 

One dimentional array with random values :  
 [2 1 3 3 3 1 0 4 0 2] 

Two dimentional

#### 12. Mean, Median Variance, Standard deviation 

In [2]:
arr12 = np.arange(0,15)
print('Mean                 : ', np.mean(arr12))        # Mean
print('Median               : ', np.median(arr12))      # Median
print('Standard Deviation   : ', np.std(arr12))         # Standard Deviation
print('Variance             : ', np.var(arr12),'\n')         # Variance

Mean                 :  7.0
Median               :  7.0
Standard Deviation   :  4.320493798938574
Variance             :  18.666666666666668 



### **3 Accessing the entries of a Numpy Array**

In [93]:
# Array
rand_arr = np.random.randint(10,99,10)
print(rand_arr,'\n')

print(rand_arr[6])                          # Index wise access
print(rand_arr[4:8])                        # Range wise access
print(rand_arr[np.arange(3,10,3)],'\n')     # Access multiple index at once

print('Values greater than 50 : ', rand_arr[rand_arr<50])       # Access index with condition
print('Values smaller than 50 : ', rand_arr[rand_arr>50],'\n')  # Access index with condition

# Matrix
rand_matrix = np.random.randint(10,99,[5,8])
print(rand_matrix,'\n')

print('Row access   : ','\n',rand_matrix[3])
print('Index access : ',rand_matrix[3][3]) #OR
print('Index access : ',rand_matrix[3,4])
print('Access Specific rows and specific column : ','\n',rand_matrix[0:2,1:3])

print('Values greater than 50 : ', rand_matrix[rand_matrix<50])       # Access index with condition
print('Values smaller than 50 : ', rand_matrix[rand_matrix>50],'\n')  # Access index with condition


[12 36 77 40 56 69 24 93 57 58] 

24
[56 69 24 93]
[40 24 58] 

Values greater than 50 :  [12 36 40 24]
Values smaller than 50 :  [77 56 69 93 57 58] 

[[36 11 84 39 95 24 20 60]
 [44 27 62 54 76 50 95 60]
 [57 72 90 38 58 88 17 20]
 [42 14 58 95 17 34 71 56]
 [61 68 77 17 29 76 64 73]] 

Row access   :  
 [42 14 58 95 17 34 71 56]
Index access :  95
Index access :  17
Access Specific rows and specific column :  
 [[11 84]
 [27 62]]
Values greater than 50 :  [36 11 39 24 20 44 27 38 17 20 42 14 17 34 17 29]
Values smaller than 50 :  [84 95 60 62 54 76 95 60 57 72 90 58 88 58 95 71 56 61 68 77 76 64 73] 



### **4 Modifying the entries of a Numpy Matrix**

In [102]:
rand_mat = np.random.randint(10,99,[5,8])
print('Before Modification :', '\n', rand_mat,'\n')

rand_mat[1:3,3:5] = 0
print('After Modification  : ', '\n', rand_mat,'\n')

rand_mat[2:] = 88
print('After rows Modification  : ', '\n', rand_mat,'\n')

rand_mat[:3] = 77
print('After column Modification  : ', '\n', rand_mat,'\n')

rand_mat[:] = 100
print('After all Modification  : ', '\n', rand_mat,'\n')


Before Modification : 
 [[25 25 64 25 24 20 13 81]
 [97 17 22 73 91 86 64 82]
 [81 30 70 31 43 49 70 58]
 [33 86 75 76 26 34 73 58]
 [69 97 13 36 44 80 44 96]] 

After Modification  :  
 [[25 25 64 25 24 20 13 81]
 [97 17 22  0  0 86 64 82]
 [81 30 70  0  0 49 70 58]
 [33 86 75 76 26 34 73 58]
 [69 97 13 36 44 80 44 96]] 

After rows Modification  :  
 [[25 25 64 25 24 20 13 81]
 [97 17 22  0  0 86 64 82]
 [88 88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88 88]] 

After column Modification  :  
 [[77 77 77 77 77 77 77 77]
 [77 77 77 77 77 77 77 77]
 [77 77 77 77 77 77 77 77]
 [88 88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88 88]] 

After all Modification  :  
 [[100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]] 



### **4 Store a matrix and load stored matrix of a Numpy array**

In [14]:
rand_mat1 = np.random.randint(10,99,[5,8])
print('Before Storing :', '\n', rand_mat1,'\n')
rand_mat2 = np.random.randint(10,99,[5,8])
print('Before Storing :', '\n', rand_mat2,'\n')

# store a sinlge matrix and load saved matrix    
np.save('savedFiles',rand_mat1)                                        
loaded_mat = np.load('savedFiles.npy')
print('After loding stored data :','\n' ,loaded_mat, '\n')

# Store multiple matrix and load stored matrix 
np.savez('multiFile',rand_mat1=rand_mat1,rand_mat2=rand_mat2)           
loaded_mat = np.load('multifile.npz')                                  
print('1st Matrix: \n',loaded_mat['rand_mat1'])
print('2nd Matrix: \n',loaded_mat['rand_mat2'], '\n')

# Store in text file and load stored textfile
np.savetxt('savedText.txt', rand_mat1, delimiter=',')
loaded_mat = np.loadtxt('savedText.txt', delimiter=',')
print('Ater loading saced text file','\n', loaded_mat)


Before Storing : 
 [[34 95 74 56 38 45 25 28]
 [41 59 63 66 94 54 42 42]
 [26 25 37 41 64 53 34 87]
 [10 95 84 84 64 10 85 55]
 [89 22 33 89 26 70 60 58]] 

Before Storing : 
 [[45 67 13 66 58 69 11 41]
 [39 25 17 38 16 91 58 37]
 [60 14 55 35 41 64 86 85]
 [61 72 77 62 32 92 93 82]
 [82 18 20 37 37 10 93 43]] 

After loding stored data : 
 [[34 95 74 56 38 45 25 28]
 [41 59 63 66 94 54 42 42]
 [26 25 37 41 64 53 34 87]
 [10 95 84 84 64 10 85 55]
 [89 22 33 89 26 70 60 58]] 

1st Matrix: 
 [[34 95 74 56 38 45 25 28]
 [41 59 63 66 94 54 42 42]
 [26 25 37 41 64 53 34 87]
 [10 95 84 84 64 10 85 55]
 [89 22 33 89 26 70 60 58]]
2nd Matrix: 
 [[45 67 13 66 58 69 11 41]
 [39 25 17 38 16 91 58 37]
 [60 14 55 35 41 64 86 85]
 [61 72 77 62 32 92 93 82]
 [82 18 20 37 37 10 93 43]] 

Ater loading saced text file 
 [[34. 95. 74. 56. 38. 45. 25. 28.]
 [41. 59. 63. 66. 94. 54. 42. 42.]
 [26. 25. 37. 41. 64. 53. 34. 87.]
 [10. 95. 84. 84. 64. 10. 85. 55.]
 [89. 22. 33. 89. 26. 70. 60. 58.]]
